### ISSUE TITLE
PVC is templated incorrectly

### ISSUE THREAD

**Issue by uhthomas** [mend/renovate-on-prem#225]
The "cachePersistence" config generates an invalid PVC.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: some-name
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
    storageClassName: "some-storage-class-name"
```

The `storageClassName` field should not be a part of resources, but as part of the spec.

```diff
- spec.resources.storageClassName
+ spec.storageClassName
```
