### ISSUE TITLE
Publish helm chart on ArtifactHub

### ISSUE THREAD

**Issue by k-jingyang** [mend/renovate-on-prem#235]
Hello,

Would it be possible to publish the helm chart onto ArtifactHub as a verified repository?

This has been done for renovate's helm chart (not renovate-on-prem) as per https://github.com/renovatebot/helm-charts/blob/gh-pages/artifacthub-repo.yml.

Thanks!

**Comment by rarkins** [comment]
PRs welcome if this is just a matter of modifying the github action

**Comment by k-jingyang** [comment]
> PRs welcome if this is just a matter of modifying the github action

Sadly, this cannot be done via PR. 😞 

You or a maintainer will have to 
1. Login to https://artifacthub.io/
2. Top right hand corner, profile button > `Control Panel`
3. Go to the `Organization` tab > `Add an Organization`
    - Possibly using "mend" as the organization name?
5. Switch `Control Panel Context` to "mend"
6. Go to `Repositories` tab > `Add Repository`
    - Fill in the details
    - For URL, it should be https://mend.github.io/renovate-on-prem

Once this is done, we can create the following file in the `gh-pages` branch

```yaml
# Artifact Hub repository metadata file
repositoryID: The ID of the Artifact Hub repository
owners: # (optional, used to claim repository ownership)
  - name: rarkins
    email: rhys@arkins.net
```

I hope these steps makes it easier on you to make the change. 😄 

Publishing the chart onto ArtifactHub and making the chart verified will definitely help with discoverability and compliance. Thanks a bunch!
