### ISSUE TITLE
Ingress rules with AWS ALB don't work out of the box

### ISSUE THREAD

**Issue by rubyisbeautiful** [mend/renovate-on-prem#252]
I [installed the new ALB controller](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) and updated my ingress to look like
```yaml
ingress:
  enabled: true
  ingressClassName: alb
 
  annotations: {
    "alb.ingress.kubernetes.io/load-balancer-name": "renovate",
    "alb.ingress.kubernetes.io/scheme": "internet-facing",
    "alb.ingress.kubernetes.io/subnets": "subnet-0123abc,subnet-0123xyz",
    "alb.ingress.kubernetes.io/target-type": "ip"
  }

  hosts:
    - renovate-0123456789.us-west-2.elb.amazonaws.com # fake
  tls: []
```
which produces the Ingress:
```yaml
spec:
  ingressClassName: alb
  rules:
  - host: renovate-0123456789.us-west-2.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: renovate
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
```

This creates a rule in the ALB listener that is an exact match to /, making e.g. the /webhook not work.  It works if I modify the rule in the listener in AWS directly, to match i.e. paths / or /webhook.  

Because the rules section of the Ingress spec is hardcoded, I can't fix this using just annotations/rules.  The rules section could default to that if no rules are provided in the values.  

I may have misconfigured something; if not, I can attempt a PR
