### ISSUE TITLE
Artifact update problem - package-lock.json

### ISSUE THREAD

**Issue by paymand** [mend/renovate-on-prem#317]
Hi,

I'm using self hosted renovate-whitesource version `4.0.0`.
The PRs that are created do not contain an updated `package-lock.json` and I see this error:

**File name: package-lock.json**
```
/usr/local/bin/npm: line 4: .: filename argument required
.: usage: . filename [arguments]
/usr/local/bin/npm: line 6: /opt/containerbase/tools/npm/8.19.4/bin/npm: No such file or directory
```

I did a bit of debugging and when I run the `npm --version` command inside the container, I'm getting:
```
ubuntu@renovate-whitesource-renovate-79f8c64f7c-5mcrd:/usr/src/app$ npm --version
/usr/local/bin/npm: line 6: /opt/containerbase/tools/npm/8.19.4/bin/npm: No such file or directory
```
Looks like we have 2 npm folders:
```
ubuntu@renovate-whitesource-renovate-79f8c64f7c-24hwd:/usr/src/app$ ls /opt/containerbase/tools/npm
8.19.4  9.7.2
```
and the folder to which `/usr/loca/bin/npm` is pointing is empty (the other one, i.e., 9.7.2 is good though):
```
ubuntu@renovate-whitesource-renovate-79f8c64f7c-24hwd:/usr/src/app$ ls -alh /opt/containerbase/tools/npm/8.19.4
total 0
drwxrwxr-x 2 ubuntu root  6 Sep 20 12:21 .
drwxrwxr-x 1 root   root 20 Sep 20 12:21 ..
ubuntu@renovate-whitesource-renovate-79f8c64f7c-24hwd:/usr/src/app$ ls -alh /opt/containerbase/tools/npm/9.7.2/
total 80K
drwxr-xr-x 3 root root  82 Aug 15 07:43 .
drwxrwxr-x 1 root root  20 Sep 20 12:21 ..
lrwxrwxrwx 1 root root  52 Aug 15 07:43 bin -> /opt/containerbase/tools/npm/9.7.2/node_modules/.bin
drwxr-xr-x 4 root root  55 Aug 15 07:43 node_modules
-rw-r--r-- 1 root root 73K Aug 15 07:43 package-lock.json
-rw-r--r-- 1 root root  47 Aug 15 07:43 package.json
```
The content of `/usr/local/bin/npm` is:
```
ubuntu@renovate-whitesource-renovate-79f8c64f7c-24hwd:/usr/src/app$ cat /usr/local/bin/npm
#!/bin/bash

    if [[ -z "${CONTAINERBASE_ENV+x}" ]]; then
      . $ENV_FILE
    fi
    /opt/containerbase/tools/npm/8.19.4/bin/npm "$@"
```
so looks like it's hard-coded to use a "non-existing" file.

Could you take a look please?
Let me know if you need more info, config, logs, etc.

**Comment by rarkins** [comment]
@viceice do you recall if this is the same as we saw previously and you fixed in Containerbase? If so then I need to check if the latest on-prem has that fix. Strange if nobody has reported it though.

**Comment by viceice** [comment]
looks like you need to update containerbase image

**Comment by paymand** [comment]
@rarkins could you release a new version with the updated container base image?

**Comment by rarkins** [comment]
The latest renovate on-prem is using Containerbase v9.10.4. Combined changelog since then: https://octoclairvoyant.vercel.app/comparator?repo=containerbase%2Fbase&from=9.10.4&to=latest

@viceice I don't spot any bug fixes for this in there - wasn't it earlier?

**Comment by rarkins** [comment]
Running against `whitesource/renovate:5.0.1`:

```
ubuntu@400a350b7b3b:/usr/src/app$ node --version
v18.16.1
ubuntu@400a350b7b3b:/usr/src/app$ npm --version
9.7.2
ubuntu@400a350b7b3b:/usr/src/app$ which npm
/usr/local/bin/npm
ubuntu@400a350b7b3b:/usr/src/app$ install-tool npm 8.19.4
[07:33:08.928] INFO (47): Installing tool npm v8.19.4...
8.19.4
[07:33:24.017] INFO (47): Installed tool npm in 15s.
ubuntu@400a350b7b3b:/usr/src/app$ which npm
/usr/local/bin/npm
ubuntu@400a350b7b3b:/usr/src/app$ npm --version
8.19.4
ubuntu@400a350b7b3b:/usr/src/app$ ls /opt/containerbase/tools/npm
8.19.4  9.7.2
ubuntu@400a350b7b3b:/usr/src/app$ ls -alh /opt/containerbase/tools/npm/8.19.4
total 76K
drwxrwxr-x 3 ubuntu root 4.0K Sep 21 07:33 .
drwxrwxr-x 1 root   root 4.0K Sep 21 07:33 ..
lrwxrwxrwx 1 ubuntu root   53 Sep 21 07:33 bin -> /opt/containerbase/tools/npm/8.19.4/node_modules/.bin
drwxr-xr-x 4 ubuntu root 4.0K Sep 21 07:33 node_modules
-rw-r--r-- 1 ubuntu root  60K Sep 21 07:33 package-lock.json
-rw-r--r-- 1 ubuntu root   48 Sep 21 07:33 package.json
ubuntu@400a350b7b3b:/usr/src/app$
```

Summarizing:
- If you have an npm 8.19.4 folder then it's because Renovate has tried to install that at runtime
- It looks like the installation has _failed_, leaving an empty folder

Naturally this state is not ideal, but it's hard to tell why unless you have the logs from when that `install-tool npm 8.19.4` was run the first time.

Does your environment allow internet connections for downloading of packages? This is necessary to support the binarySource=install behavior of dynamic package manager install. If not then you need to configure `RENOVATE_BINARY_SOURCE=global` instead and just stick with the pre-installed options.

If your environment does support it, and this was a temporary problem, then if you recreate the container it should be back to default state.

**Comment by rarkins** [comment]
In short, a containerbase upgrade + on-prem release is likely not the solution to the problem you have (although it may appear to fix it because any recreation of the container might)

**Comment by paymand** [comment]
so the logs:
```
"stack": "ExecError: Command failed: install-tool npm 8.19.4
/usr/local/bin/npm: line 4: .: filename argument required
.: usage: . filename [arguments]
/usr/local/bin/npm: line 6: /opt/containerbase/tools/npm/8.19.4/bin/npm: No such file or directory
```

and:
```
"stdout": "[12:21:55.136] INFO (162): Installing tool npm v8.19.4...
[12:21:56.214] FATAL (162): Command failed with exit code 1: /opt/containerbase/tools/node/18.16.1/bin/npm install npm@8.19.4 --save-exact --no-audit --prefix /opt/containerbase/tools/npm/8.19.4 --cache /tmp/containerbase-npm-UDTyFt --silent
    err: {
      \"type\": \"Error\",
      \"message\": \"Command failed with exit code 1: /opt/containerbase/tools/node/18.16.1/bin/npm install npm@8.19.4 --save-exact --no-audit --prefix /opt/containerbase/tools/npm/8.19.4 --cache /tmp/containerbase-npm-UDTyFt --silent\",
      \"stack\":
          Error: Command failed with exit code 1: /opt/containerbase/tools/node/18.16.1/bin/npm install npm@8.19.4 --save-exact --no-audit --prefix /opt/containerbase/tools/npm/8.19.4 --cache /tmp/containerbase-npm-UDTyFt --silent
              at makeError (/snapshot/dist/containerbase-cli.js:40996:13)
              at handlePromise (/snapshot/dist/containerbase-cli.js:41452:29)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async InstallNpmService.install (/snapshot/dist/containerbase-cli.js:42380:5)
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:42693:9)
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:42779:14)
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1344:26)
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2457:22)
              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2465:28)
              at async main (/snapshot/dist/containerbase-cli.js:42939:3)
      \"shortMessage\": \"Command failed with exit code 1: /opt/containerbase/tools/node/18.16.1/bin/npm install npm@8.19.4 --save-exact --no-audit --prefix /opt/containerbase/tools/npm/8.19.4 --cache /tmp/containerbase-npm-UDTyFt --silent\",
      \"command\": \"/opt/containerbase/tools/node/18.16.1/bin/npm install npm@8.19.4 --save-exact --no-audit --prefix /opt/containerbase/tools/npm/8.19.4 --cache /tmp/containerbase-npm-UDTyFt --silent\",
      \"escapedCommand\": \"\\\"/opt/containerbase/tools/node/18.16.1/bin/npm\\\" install \\\"npm@8.19.4\\\" --save-exact --no-audit --prefix \\\"/opt/containerbase/tools/npm/8.19.4\\\" --cache \\\"/tmp/containerbase-npm-UDTyFt\\\" --silent\",
      \"exitCode\": 1,
      \"cwd\": \"/tmp/renovate/github/peakon/control\",
      \"failed\": true,
      \"timedOut\": false,
      \"isCanceled\": false,
      \"killed\": false
    }
[12:21:56.216] INFO (162): Installed tool npm with errors in 1s.
",
```

it might be because:
```
ubuntu@renovate-whitesource-renovate-56f4884b89-n76rj:/usr/src/app$ ls -al /opt/containerbase/tools/npm
total 0
drwxrwxr-x 3 root root 19 Aug 15 07:43 .
drwxrwxr-x 1 root root 18 Aug 15 07:56 ..
drwxr-xr-x 3 root root 82 Aug 15 07:43 9.7.2
ubuntu@renovate-whitesource-renovate-56f4884b89-n76rj:/usr/src/app$ whoami
ubuntu
```

**Comment by paymand** [comment]
Background: I'm using [Mend Renovate On-Prem helm chart](https://github.com/mend/renovate-on-prem/tree/main/helm-charts/whitesource-renovate):
Chart.yaml:
```
---
apiVersion: v2
name: renovate
description: A Helm chart for deploying Mend Renovate On-Premises
type: application
version: 0.0.2
appVersion: "1.0"
dependencies:
- name: whitesource-renovate
  version: 4.0.0
  repository: https://mend.github.io/renovate-on-prem
```

values.yaml:
```
region: eu-west-1
clusterName: ci

whitesource-renovate:
  renovate:
    logLevel: debug
    renovate:
    renovatePlatform: "github"
    acceptWhiteSourceTos: "y"
    renovateEndpoint: "https://api.github.com/"
    existingSecret: renovate
    npmrc: |
      registry= REDACTED
      always-auth=true
      email= REDACTED
    extraEnvVars:
      - name: RENOVATE_USERNAME
        value: "REDACTED"
      - name: RENOVATE_GIT_AUTHOR
        value: "REDACTED"
      - name: RENOVATE_PLATFORM_COMMIT
        value: "true"
      - name: RENOVATE_NPMRC_MERGE
        value: "true"
      - name: RENOVATE_REPOSITORIES
        value: "REDACTED # comma separated list of repos
      - name: RENOVATE_AUTODISCOVER
        value: "true"
      - name: RENOVATE_AUTODISCOVER_FILTER
        value: "REDACTED" # comma separated list of filters
      - name: RENOVATE_CONFIG_FILE
        value: "/mnt/secrets-store/config.json"
      - name: RENOVATE_DETECT_GLOBAL_MANAGER_CONFIG
        value: "true"
  podSecurityContext:
    fsGroup: 1000
  extraVolumes:
  - name: secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: renovate
  extraVolumeMounts:
  - name: secrets
    mountPath: "/mnt/secrets-store"
    readOnly: true
```
